services:
  - type: web
    name: copad-signaling
    runtime: node
    rootDir: signaling
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
